name: 发布到 npm
on:
  push:
    branches: '*'
  workflow_dispatch: # 手动触发
    inputs:
      version:
        description: '触发原因（选填）'
        required: false
        default: '手动触发'
      ref:
        description: '触发的分支（选填，默认为当前分支）'
        required: false
        default: ''

# 新的 OpenID Connect 验证方式
# 无需手动填写 NODE_AUTH_TOKEN 且定期更换
permissions:
  id-token: write # 唯一必须的权限：启用 OIDC
  contents: read # write 必须，克隆代码库权限
  # packages: write

jobs:
  pub:
    # 在提交的代码包含 `version` 字样时才运行该动作
    # 或者手动触发
    name: |
      发布到 npm
    runs-on: ubuntu-latest
    # 复合条件判断（自动触发检查提交信息，手动触发直接放行）
    # contains : 检查字符串是否包含指定字符串
    # startsWith : 检查字符串是否以指定字符串开头
    # endsWith : 检查字符串是否以指定字符串结尾

    if: |
      (github.event_name == 'push' && startsWith(github.event.head_commit.message, 'version')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: 代码检出
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}
          fetch-depth: 1

      - name: 初始化 Node 并设定 Node 版本
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: 清理旧的用户令牌
        run: |
          npm config delete //registry.npmjs.org/:_authToken
          rm -f ~/.npmrc
        shell: bash

      - name: pnpm 安装
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: 缓存 pnpm
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 发布到 npm
        env:
          NPM_CONFIG_USERCONFIG: /dev/null # 强制忽略本地配置
          # NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          chmod +x ./scripts/pub.sh
          ./scripts/pub.sh
